### PR TITLE
Update build.gradle (#16)

### PR DESCRIPTION
**Pull request by Donnnno**
Removed license dependency

### CODE REVIEW

**Comment by Donnnno** [comment]
Great to see that you're updating Snow! :)

**Comment by Donnnno** [comment]
@baitmooth you should work in the main repo and not in my fork 😅

**Comment by baitmooth** [comment]
this weird. cuz I do work on only my repo…

**Comment by baitmooth** [comment]
… and if you close this PR? looks like all i do on main ends up in this PR

**Comment by Donnnno** [comment]
Strange!

**Pull request closed without merging**
